# Generated by Django 4.2.4 on 2023-08-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
    ]
