# Generated by Django 4.2.4 on 2023-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
