# Generated by Django 4.2.4 on 2023-08-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to=settings.AUTH_USER_MODEL),
        ),
    ]
