# Generated by Django 4.2.4 on 2023-08-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_img_url_remove_product_img_url'),
        ('bucket', '0002_alter_userprofileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to='post.post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to='post.product'),
        ),
    ]
